DiamFinal/DiamFinal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MyApp.urls')),
]

DiamFinal/MyApp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from .views import index


app_name = 'MyApp'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('reset/', views.reset, name='reset'),
    path('aboutUs/', views.about_view, name='aboutUs'),
    path('information/', views.information_view, name='information'),
    path('anunciar/', views.anunciar_view, name='anunciar'),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name="register"),
    path('<int:boleia_id>', views.detalhes, name='detalhes'),
    path('user_info/', views.user_info_view, name='user_info'),
    path('cancelar_vaga/<int:boleia_id>/<int:user_id>/', views.cancelar_vaga, name='cancelar_vaga'),
    path('editar/<int:boleia_id>/', views.editar_boleia, name='editar_boleia'),
    path('remover_boleia/<int:boleia_id>/', views.remover_boleia, name='remover_boleia'),
]

DiamFinal/MyApp/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime
from django.contrib.auth.models import User

class CustomUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=30, null=True)
    last_name = models.CharField(max_length=30, null=True)
    car_brand = models.CharField(max_length=30, null=True)
    car_model = models.CharField(max_length=30, null=True)

class Boleia(models.Model):
    motorista = models.ForeignKey(User, on_delete=models.CASCADE, related_name='boleias_as_motorista')
    users = models.ManyToManyField(User, blank=True, related_name='boleias_as_passageiro')
    partida = models.CharField(max_length=255)
    chegada = models.CharField(max_length=255)
    horario = models.DateTimeField()
    preco = models.DecimalField(max_digits=8, decimal_places=2)
    vagas = models.IntegerField()
    detalhes = models.TextField(blank=True)

DiamFinal/MyApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User, Permission
from .models import CustomUser, Boleia


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=100, required=True)
    last_name = forms.CharField(max_length=100, required=True)
    car_brand = forms.CharField(max_length=100, required=True)
    car_model = forms.CharField(max_length=100, required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name', 'car_brand', 'car_model')

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        customUser = CustomUser(user=user, car_brand=self.cleaned_data['car_brand'], car_model=self.cleaned_data['car_model'])
        if commit:
            user.save()
            customUser.save()

        user.save()
        customUser.save()
        return user

class BoleiaForm(forms.ModelForm):
    class Meta:
        model = Boleia
        fields = ['partida', 'chegada', 'horario', 'preco', 'vagas', 'detalhes']

    horario = forms.DateTimeField(
        label='Data e hora da boleia (d/m/Y H:M)',
        input_formats=['%d/%m/%Y %H:%M'],
        widget=forms.DateTimeInput(attrs={
            'class': 'form-control datetimepicker-input',
            'data-target': '#datetimepicker1'
        })
    )
class EditBoleiaForm(forms.ModelForm):
    class Meta:
        model = Boleia
        fields = ['partida', 'chegada', 'horario', 'preco', 'vagas', 'detalhes']

    horario = forms.DateTimeField(
        label='Data e hora da boleia (d/m/Y H:M)',
        input_formats=['%d/%m/%Y %H:%M'],
        widget=forms.DateTimeInput(attrs={
            'class': 'form-control datetimepicker-input',
            'data-target': '#datetimepicker1'
        })
    )
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].required = False



    def clean_vagas(self):
        vagas = self.cleaned_data.get('vagas')
        users_count = self.instance.users.count()
        if vagas < users_count:
            raise forms.ValidationError(
                f"Não é possível reduzir as vagas para menos do que {users_count} utilizadores já confirmados na boleia.")
        return vagas

DiamFinal/MyApp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from .models import Boleia
from django.http import JsonResponse
from django.urls import reverse
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from .forms import RegistrationForm
from .forms import BoleiaForm, EditBoleiaForm
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.models import User

# Create your views here.

#@login_required(login_url='/MyApp/login')
def index(request):
    boleias = Boleia.objects.all()
    template = loader.get_template('MyApp/index.html')
    context = {'boleias': boleias}
    return render(request, 'MyApp/index.html', context)


def search(request):
    partida = request.GET.get('partida')
    chegada = request.GET.get('chegada')

    if partida and chegada:
        boleias = Boleia.objects.filter(partida__iexact=partida, chegada__iexact=chegada)
    else:
        if partida:
            boleias = Boleia.objects.filter(partida__iexact=partida)
        else:
            if chegada:
                boleias = Boleia.objects.filter(chegada__iexact=chegada)

            else:
                # Fetch all Boleia objects
                boleias = Boleia.objects.all()

    return render(request, 'MyApp/index.html', {'boleias': boleias})


def reset(request):
    boleias = Boleia.objects.all()
    return render(request, 'MyApp/index.html', {'boleias': boleias})


def about_view(request):
    return render(request, 'MyApp/aboutUs.html')


def information_view(request):
    return render(request, 'MyApp/information.html')


def anunciar_view(request):
    if request.method == 'POST':
        form = BoleiaForm(request.POST)
        if form.is_valid():
            partida = form.cleaned_data['partida']
            chegada = form.cleaned_data['chegada']
            horario = form.cleaned_data['horario']
            preco = form.cleaned_data['preco']
            vagas = form.cleaned_data['vagas']
            detalhes = form.cleaned_data['detalhes']
            nova_boleia = Boleia(partida=partida, chegada=chegada, horario=horario, preco=preco, vagas=vagas, detalhes=detalhes)
            nova_boleia.motorista = request.user
            nova_boleia.save()
            return HttpResponseRedirect(reverse('MyApp:index'))
    else:
        form = BoleiaForm()
    return render(request, 'MyApp/anunciar.html', {'form': form})

def detalhes(request, boleia_id):
    boleia = get_object_or_404(Boleia, pk=boleia_id)
    if request.method == 'POST':
        if request.user not in boleia.users.all():
            boleia.vagas -= 1
            boleia.users.add(request.user)
            boleia.save()
            return HttpResponseRedirect(reverse('MyApp:detalhes', args=(boleia_id,)))
        # else:
        #     return render(request, 'MyApp/detalhe.html', {'already_in_boleia': "The user is already registered in this ride"})

    return render(request, 'MyApp/detalhe.html', {'boleia': boleia})


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('MyApp:index'))
        else:
            return render(request, 'MyApp/login.html', {'error_message': 'Invalid login credentials'})
    else:
        return render(request, 'MyApp/login.html')

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('MyApp:login'))


def register_view(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            email = request.POST['email']
            print(email)
            print(username)
            if User.objects.filter(email=email).exists():
                return render(request, 'MyApp/register.html', {'register_error1': "Email already in use"})
            else:
                form.save()
                return HttpResponseRedirect(reverse('MyApp:index'))
        else:
            username = request.POST['username']
            email = request.POST['email']
            if User.objects.filter(email=email).exists():
                return render(request, 'MyApp/register.html', {'register_error1': "Username and email already in use"})
            return render(request,'MyApp/register.html', {'register_error1': "Username already taken"})
    else:
        form = RegistrationForm()
    return render(request, 'MyApp/register.html', {'form': form})


def user_info_view(request):
    user = request.user
    user_boleias = Boleia.objects.filter(users=user)
    motoristas = Boleia.objects.filter(motorista=user)
    context = {
        'user': user,
        'boleias': user_boleias,
        'motoristas':motoristas
    }

    return render(request, 'MyApp/user_info.html',context)

def editar_boleia(request, boleia_id):
    boleia = get_object_or_404(Boleia, id=boleia_id, motorista=request.user)
    if request.method == 'POST':

        form = EditBoleiaForm(instance=boleia)
        if form.is_valid():
            form.save()
            messages.success(request, 'Boleia atualizada com sucesso.')
            render(request, 'MyApp/detalhe.html', {'boleia': boleia})
    else:
        form = EditBoleiaForm(instance=boleia)
    return render(request, 'MyApp/anunciar.html', {'form': form})

def cancelar_vaga(request, boleia_id, user_id):
    boleia = get_object_or_404(Boleia, pk=boleia_id)
    user = get_object_or_404(User, pk=user_id)
    if user in boleia.users.all():
        boleia.users.remove(user)
        boleia.vagas += 1
        boleia.save()
    return render(request, 'MyApp/detalhe.html', {'boleia': boleia})

def remover_boleia(request, boleia_id):
    boleia = get_object_or_404(Boleia, pk=boleia_id)
    boleia.delete()
    return HttpResponseRedirect(reverse('MyApp:user_info'))

DiamFinal/MyApp/templates/MyApp/aboutUs.html
{% extends "MyApp/index.html" %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>UniRide</title>
</head>
<body>
{% block content %}
<div class="aboutUs">
    <h1>About Us</h1>
<br>
  <p>
    Bem-vindos ao UniRide,
  </p>

    <br>
  <p>
      Esta ideia nasceu a partir de um projeto na cadeira de Desenvolvimento para a Internet e Aplicações Móveis.
      </p>
    <br>
    <p>
      Queríamos que o nosso projeto conseguisse ser aplicado na vida real e que conseguisse ajudar as pessoas.
      Assim surgiu a nossa ideia, criar um website para Alunos das faculdades de Portugal, em que conseguissem apanhar boleias de outros alunos e oferecer boleias a outros alunos.
  </p>
    <br>
    <p> Vantagens de utilizar o UniRide:</p>
    <br>
        <ul>
            <li>Poupar nas deslocações</li>
            <li>Fazer novas amizades <3</li>
            <li>Diminuir emissões nocivas para a atmosfera</li>
        </ul>

    <br>
    <span>Criadores: </span>
        <p>Matheus Quintas & Alexandra Monteiro</p>

</div>

{% endblock %}
</body>
</html>

DiamFinal/MyApp/templates/MyApp/anunciar.html
{% extends "MyApp/index.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>UniRide</title>
</head>
<body>
{% block content %}
 <div class="anunciar-form">
  <h2>Anunciar Boleia</h2>
  <form id="anunciar-form" method="post">
    {% csrf_token %}

    <div class="form-group">
      <label for="partida">Partida:</label>
      <input type="text" id="partida" name="partida" required>
    </div>
    <div class="form-group">
      <label for="chegada">Chegada:</label>
      <input type="text" id="chegada" name="chegada" required>
    </div>
      <div class="form-group">
      <label for="chegada">Vagas:</label>
      <input type="text" id="vagas" name="vagas" required>

    </div>
      <div class="form-group">
      <label for="preco">Preço:</label>
      <input type="text" id="preco" name="preco" required>
    </div>
      <div class="form-group">
      <label for="horario">Data:</label>
      <input type="datetime-local" id="horario" name="horario" required>
    </div>
      <div class="form-group">
      <label for="detalhes">Detalhes:</label>
      <input type="text" id="detalhes" name="detalhes" required>
    </div>

      <button id="anunciar-form-button" type="submit">Anunciar boleia</button>
  </form>
</div>

{% endblock %}
</body>
</html>

DiamFinal/MyApp/templates/MyApp/detalhe.html
{% extends "MyApp/index.html" %}
<html lang="en">
<head>

</head>
<body>
{% block content %}
    <section class="detail">
    <div class="butoes_detail">
        {% if request.user == boleia.motorista or user.is_superuser %}
        <a href="{% url 'MyApp:remover_boleia' boleia.id %}">
            <button type="submit">Remover Boleia</button>
        </a>
      {% endif %}
    </div>
        <ul class="detalhes_ul">
            <li class="color1">
                  <h1> Boleia de {{ boleia.partida }} para {{ boleia.chegada }} </h1>
                  <h2> Horário: {{ boleia.horario }} </h2>
            </li>

 <li class="color2">
        <h2> Detalhes: </h2>
      <h3> {{ boleia.detalhes }}</h3>
            </li>

 <li class="color1">
       <h2> Motorista: </h2>
      <h3> {{boleia.motorista}} </h3>
            </li>

 <li class="color2">
        <h2> Email do motorista: </h2>
      <h3> {{boleia.motorista.email}} </h3>
            </li>

 <li class="color1">
                 <h2> Preço: {{ boleia.preco }}€</h2>
            </li>
      <li class="color2">
             <h2> Vagas: {{ boleia.vagas }}</h2>
            </li>

 <li class="color1">
     {% if request.user == boleia.motorista or user.is_superuser %}
        {% if boleia.users.all.exists %}
            <h2>Passageiros</h2>
            <ul>
                {% for passageiro in boleia.users.all %}
                <li>{{ passageiro.username }} - {{ passageiro.first_name }} {{ passageiro.last_name }}</li>
                {% endfor %}
            </ul>
     {% else %}
            <h3>Ainda não há vagas reservadas.</h3>
        {% endif %}
     {% endif %}
            </li>
        </ul>

      {% if not request.user == boleia.motorista %}
        {% if boleia.vagas > 0 %}
      <form method="post" action="{% url 'MyApp:detalhes' boleia_id=boleia.id %}">
        {% csrf_token %}
          {% if user.is_authenticated %}
        <button type="submit">Reservar vaga</button>
          {% else %}
          <button><a style="color: beige;" href="{% url 'MyApp:login' %}">
                  Reservar vaga
          </a></button>

          {% endif %}
      </form>
      {% else %}
        <p>Não há mais vagas disponíveis nesta boleia.</p>
      {% endif %}
      {% endif %}

      {% if boleia.users.all.exists %}
        {% for passageiro in boleia.users.all %}
             {% if request.user == passageiro %}
                <form method="post" action="{% url 'MyApp:cancelar_vaga' boleia_id=boleia.id user_id=user.id %}">
                {% csrf_token %}
                    <button type="submit">Cancelar reserva from {{ request.user.username }}</button>
                </form>
             {% endif %}
        {% endfor %}
      {% endif %}

      {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
      {% endif %}
    </section>
{% endblock %}
</body>
</html>

DiamFinal/MyApp/templates/MyApp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>UniRide</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.8.0/gsap.min.js"></script>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'MyApp/styles.css' %}" />
    <script src="https://cdn.jsdelivr.net/npm/kute.js@2.2.2/dist/kute.min.js"></script>
</head>
<body>
    <div class="off-screen-menu">
        <a href="{% url 'MyApp:aboutUs' %}">About Us</a>
<!--        <a href="{% url 'MyApp:information' %}">Information</a>-->
    </div>

<nav>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 250">
        <path fill="#273036" fill-opacity="1" d="M0,192L26.7,181.3C53.3,171,107,149,160,154.7C213.3,160,267,192,320,197.3C373.3,203,427,181,480,154.7C533.3,128,587,96,640,112C693.3,128,747,192,800,213.3C853.3,235,907,213,960,192C1013.3,171,1067,149,1120,154.7C1173.3,160,1227,192,1280,197.3C1333.3,203,1387,181,1413,170.7L1440,160L1440,0L1413.3,0C1386.7,0,1333,0,1280,0C1226.7,0,1173,0,1120,0C1066.7,0,1013,0,960,0C906.7,0,853,0,800,0C746.7,0,693,0,640,0C586.7,0,533,0,480,0C426.7,0,373,0,320,0C266.7,0,213,0,160,0C106.7,0,53,0,27,0L0,0Z"></path>
        </svg>

      <a href="{% url 'MyApp:index' %}">
            <h1 id="titulo">UniRide</h1>
        </a>

        <section class="login_OR_register">
            {% if not user.is_authenticated %}
             <a href="{% url 'MyApp:login' %}">
                <button class="butoes_nav" id="login"> LOGIN</button>
            </a>
            <a href="{% url 'MyApp:register' %}">
                <button class="butoes_nav" id="register">REGISTER</button>
            </a>
            {% else %}

            <a href="{% url 'MyApp:logout' %}">
                <button class="butoes_nav" id="logout">LOGOUT</button>
            </a>

            <a href="{% url 'MyApp:user_info' %}">
                <button class="butoes_nav" id="user_info">{{ user.username }}</button>
            </a>
            {% endif %}
        </section>
<!--        {% if not user.is_authenticated %}-->
<!--        <section class="login_OR_register">-->
<!--            <a href="{% url 'MyApp:login' %}">-->
<!--                <button class="butoes_nav" id="login"> LOGIN</button>-->
<!--            </a>-->
<!--            <a href="{% url 'MyApp:register' %}">-->
<!--                <button class="butoes_nav" id="register">REGISTER</button>-->
<!--            </a>-->
<!--        </section>-->
<!--    {% endif %}-->



    <div class="hamburger-menu">
        <div class="ham-bar bar-top"></div>
         <div class="ham-bar bar-mid"></div>
         <div class="ham-bar bar-bottom"></div>
    </div>
   <!-- img id="navbar-button" src="{% static 'media/navigation-bar.png' %}" /> -->
</nav>

{% block content %}
    <section class="searchBar">
    <form id="searchForm" class="searchBar" action="{% url 'MyApp:search' %}" method="get">
        <label class="search_label" for="partida">Local de Partida:</label>
        <input class="search_inputs" type="text" id="partida" name="partida" autocomplete="off"><br><br>

        <label class="search_label" for="chegada">Local de Chegada:</label>
        <input class="search_inputs" type="text" id="chegada" name="chegada" autocomplete="off"><br><br>

            <button id="search_button" type="submit">Pesquisar</button>
            <button id="reset_button" type="submit">Reset</button>

    </form>
</section>


<section id="anuncios_container">
    {% if boleias %}
        <table>
            <thead>
                <tr>
                    <th>Motorista</th>
                    <th>Partida</th>
                    <th>Chegada</th>
                    <th>Horário</th>
                    <th>Preço</th>
                    <th>Vagas</th>
                    <th>Detalhes</th>
                </tr>
            </thead>
            <tbody>
                {% for boleia in boleias %}
                    <tr>
                         <td>{{ boleia.motorista }}</td>
                         <td>{{ boleia.partida }}</td>
                        <td>{{ boleia.chegada }}</td>
                        <td>{{ boleia.horario }}</td>
                        <td>{{ boleia.preco }} €</td>
                        <td>{{ boleia.vagas }}</td>
                        <td>
                            <a href="{% url 'MyApp:detalhes' boleia.id %}">
                               🚘
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p style="text-align: center; font-size: 20px; margin-top: 1em; margin-bottom: 1em; position: absolute">Não existem boleias disponíveis.</p>
    {% endif %}
</section>

 <!--colocar extends nas outras páginas, na primeira linha do html -->
<!--    <svg id="blop" viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">-->
<!--  <g>-->
<!--    <path fill="#273036" d="M31.8,-42.6C43.3,-35.4,56.1,-28.9,66.5,-16.9C76.9,-4.8,85,12.7,78.2,22.8C71.3,32.9,49.6,35.6,34,35.5C18.5,35.5,9.3,32.7,-5.1,39.7C-19.4,46.7,-38.9,63.5,-51.6,62.6C-64.2,61.8,-70.1,43.2,-68.5,27.2C-66.9,11.2,-57.7,-2.3,-49.5,-12.5C-41.2,-22.6,-33.8,-29.5,-25.7,-37.8C-17.6,-46.2,-8.8,-56,0.7,-57C10.1,-57.9,20.3,-49.9,31.8,-42.6Z" transform="translate(100 100)" />-->
<!--    <a href="{% url 'MyApp:anunciar' %}">-->
<!--      <text id="anunciar" x="50" y="110" fill="#F5F5DC">Anunciar Boleia</text>-->
<!--    </a>-->
<!--  </g>-->
<!--</svg>-->
    <div class="spacer layer2 flip"></div>
    <section class="blop_anim">
        <svg id="blop" viewBox="0 0 900 600" width="900" height="600" xmlns="http://www.w3.org/2000/svg"
             xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1">
            <g transform="translate(402.57248813454015 309.19142559317913)">
                <path id="blop1" d="M129.2 -132.9C177.5 -113.5 233.5 -82.3 256.6 -33.2C279.6 16 269.7 83 227.9 109.1C186 135.2 112.3 120.5 56.8 129C1.3 137.5 -36 169.3 -71.8 168.7C-107.7 168.1 -142.2 135 -158.5 96.5C-174.9 57.9 -173.1 13.9 -173.6 -38.8C-174 -91.4 -176.7 -152.6 -148.1 -175.4C-119.6 -198.2 -59.8 -182.6 -9.6 -171.1C40.5 -159.6 81 -152.2 129.2 -132.9"
                      fill="#273036"></path>
                {% if user.is_authenticated %}
                 <a id="anunciar" href="{% url 'MyApp:anunciar' %}">
                    <text  x="-90" y="0" fill="#F5F5DC">Anunciar Boleia
                    </text>
                </a>
                {% else %}
                  <a id="anunciar" href="{% url 'MyApp:login' %}">
                    <text  x="-90" y="0" fill="#F5F5DC">Anunciar Boleia
                    </text>
                </a>
                {% endif %}
            </g>
            <g transform="translate(462.7996808603914 291.7726424536017)" style="visibility: hidden">
        <path id="blop2" d="M168.6 -187.1C208.7 -167.3 224.5 -104.9 208.6 -57.2C192.7 -9.5 145.1 23.4 113.4 53.6C81.8 83.9 66.2 111.5 34.3 145.2C2.4 178.9 -45.8 218.6 -80 210.3C-114.1 201.9 -134.1 145.5 -165.6 94.1C-197 42.7 -239.8 -3.6 -240.3 -49.5C-240.7 -95.5 -198.8 -141.2 -151.7 -159.7C-104.6 -178.3 -52.3 -169.6 6 -176.8C64.3 -183.9 128.6 -206.9 168.6 -187.1"
              fill="#273036"></path>
            </g>

        </svg>
        <script>
            const tween = KUTE.fromTo(
                '#blop1',{path: '#blop1'},
                {path: '#blop2'},
                {repeat: 999, duration: 2000, yoyo: true}
            )
            tween.start()
        </script>
    </section>
    <div class="spacer layer2"></div>

{% endblock %}
<script src="{% static 'MyApp/scripts.js' %}" type="application/javascript"></script>
</body>
</html>

DiamFinal/MyApp/templates/MyApp/information.html
{% extends "MyApp/index.html" %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>UniRide</title>
</head>
<body>
{% block content %}
<h1>info</h1>
{% endblock %}
</body>
</html>

DiamFinal/MyApp/templates/MyApp/login.html
{% extends "MyApp/index.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>UniRide</title>

</head>
<body>
{% block content %}
  <div class="login-form">
    <h2>Login</h2>
    {% if error_message %}
      <p>{{ error_message }}</p>
    {% endif %}
    <form method="post">
      {% csrf_token %}
      <label for="username">Username:</label>
      <input type="text" name="username" id="username"><br>
      <label for="password">Password:</label>
      <input type="password" name="password" id="password"><br>
      <input type="submit" value="Login" id="login-form-button">
    </form>

    <p>Don't have an account? <a href="{% url 'MyApp:register' %}">Register now!</a></p>
  </div>
{% endblock %}
</body>
</html>

DiamFinal/MyApp/templates/MyApp/register.html
{% extends "MyApp/index.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>UniRide</title>
</head>
<body>
{% block content %}
<div class="register">
    <div class="register-form">
  <h2>Register</h2>
    {% if register_error1 %}
    <p>{{ register_error1 }}</p>
    {% endif %}
  <form method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="first_name">First Name:</label>
      <input type="text" id="first_name" name="first_name" required>
    </div>
    <div class="form-group">
      <label for="last_name">Last Name:</label>
      <input type="text" id="last_name" name="last_name" required>
    </div>
    <div class="form-group">
      <label for="username">Username:</label>
      <input type="text" id="username" name="username" required>
    </div>
    <div class="form-group">
      <label for="email">Email:</label>
      <input type="email" id="email" name="email" required>
    </div>
    <div class="form-group">
      <label for="password1">Password:</label>
      <input type="password" id="password1" name="password1" required>
    </div>
    <div class="form-group">
      <label for="password2">Re-confirm:</label>
      <input type="password" id="password2" name="password2" required>
    </div>
    <div class="form-group">
      <label for="car_brand">Car Brand:</label>
      <input type="text" id="car_brand" name="car_brand" required>
    </div>
    <div class="form-group">
      <label for="car_model">Car Model:</label>
      <input type="text" id="car_model" name="car_model" required>
    </div>
    <button id="register-form-button" type="submit">Register</button>
  </form>
</div>

{% endblock %}
<a href="{% url 'MyApp:login' %}">
    <button>Fazer Login</button>
    </a>
</div>
</body>
</html>

DiamFinal/MyApp/templates/MyApp/user_info.html
{% extends "MyApp/index.html" %}
<html lang="en">
<head>

</head>
<body>
{% block content %}
 <section class="user_info">
      <h1 id="username_user"> Perfil de : {{ request.user }} </h1>
 </section>
     <div class="user_tables">
         <div class="anuncios_feitos">
             <h1>Anúncios realizados:</h1>
             <div id="anuncios_feitos_table">
                 <ul class="anuncios_feitos_ul">
                   {% if motoristas %}
                    {% for motorista in motoristas %}
                        <li>
                                <a href="{% url 'MyApp:detalhes' motorista.id %}">
                                <span> {{ motorista.partida }} - {{ motorista.chegada}}</span>
                                </a>
                        </li>
                {%endfor%}
                </ul>
                 {% else %}
                     <p>Não existem boleias disponíveis.</p>
                    {% endif %}

             </div>
         </div>

     <div class="boleias_Im_In">
         <h1>Vagas reservadas:</h1>
         <div id="boleias_Im_In_table">
            <ul class="boleias_Im_In_ul">
                    {% if boleias %}
                    {% for boleia in boleias %}
                        <li>
                                <a href="{% url 'MyApp:detalhes' boleia.id %}">
                                    <span> {{ boleia.partida }} - {{ boleia.chegada}} </span>
                                </a>

                        </li>
                    {% endfor %}
                </ul>
                 {% else %}
                    <p>Não existem boleias disponíveis.</p>
                    {% endif %}
         </div>
     </div>
     </div>

{% endblock %}
</body>
</html>